<?php
/**
 * Created by PhpStorm.
 * User: james
 * Date: 10/05/15
 * Time: 2:27 PM
 */


/**
 * Implements hook_form_FORM_ID_alter().
 */
function beehive_misc_form_system_theme_settings_alter(&$form, &$form_state, $form_id) {
  $themes_list = list_themes(TRUE);

  // Filter down to just the commons_beehive theme:
  // If commons_beehive theme exists
  // If commons_beehive is enabled
  // If we're not on the general settings tab -- because args aren't set yet
  // And we're on the commons_beehive settings page, then show the color palette
  if (isset($themes_list['commons_beehive'])
    && $themes_list['commons_beehive']->status == 1
    && !empty($form_state['build_info']['args'])
    && $form_state['build_info']['args'][0] == 'commons_beehive') {
    // Add the color palette selection form to the appearance settings form.
    require_once(drupal_get_path('theme', 'commons_beehive') . '/commons_beehive.palettes.inc');
    commons_beehive_palettes_form($form);
  }
}
